import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Studioink - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <h1 className="text-center">Hello World</h1>
    </>
  );
}
